on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-gnu  
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
